" Vim5 and later versions support syntax highlighting. Uncommenting the next

" line enables syntax highlighting by default.

set nocp

if has("syntax")

  syntax on

endif

set fenc=utf-8 
set fencs=utf-8,usc-bom,euc-jp,gb18030,gbk,gb2312,cp936 

set nocompatible 

set history=100 

set clipboard+=unnamed 

set viminfo+=! 

:highlight OverLength ctermbg=red ctermfg=white guibg=red guifg=white 
:match OverLength '\%101v.*' 

set mouse=a 
set selection=exclusive 
set selectmode=mouse,key

set showmatch 
set incsearch
set hlsearch

set wrap
"colo desert
colo torte

"syntax enable
"colorscheme monokai
"colorscheme solarized

set stal=2

:highlight green term=reverse ctermfg=3 ctermbg=2 gui=reverse guifg=slategrey guibg=khaki
:highlight reg term=reverse ctermfg=3 ctermbg=1 gui=reverse guifg=slategrey guibg=khaki
:highlight white term=reverse ctermfg=1 ctermbg=7 gui=reverse guifg=slategrey guibg=khaki cterm=bold

let Tlist_Auto_Open = 1              
let Tlist_Ctags_Cmd = '/usr/bin/ctags'  
let Tlist_Show_One_File = 1  
let Tlist_Exit_OnlyWindow = 1  
let Tlist_Use_Right_Window = 1
set tags=tags;

"let tlist_txt_settings = 'txt;c:content;f:figures;t:tables'
au BufRead,BufNewFile *.txt setlocal ft=txt

if has("autocmd")
    autocmd FileType txt setlocal ts=4 sts=4 sw=4 expandtab
endif

au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif

set  cscopetag

set cinoptions=:0
 """""""每行超过100个的字符用下划线标示""""""""
au BufRead,BufNewFile *.s,*.c,*.cpp,*.h,*.sh,*.py,*.txt,*.md,*.markdown 2match Underlined /.\%101v/
