#!/bin/bash

echo "
* 启动adbd
	./adbd&
	echo 'adb,mass_storage' > /sys/class/android_usb/android0/functions 
	echo 1 > /sys/class/android_usb/android0/enable"

echo \
"* android gadget
	echo mass_storage > /sys/class/android_usb/android0/functions
	echo /dev/nddata > /sys/devices/platform/jz4780-dwc2/dwc2/gadget/lun0/file 
	echo 1 > /sys/class/android_usb/android0/enable
"
echo \
"* 设置IP
	ifconfig eth0 192.168.2.24"

echo \
"* 设置网关
	 route add default gw 192.168.2.1"

echo \
"* 设置DNS
	 vim /etc/resolv.conf"

echo \
"
* 网络相关设置
	- ifconfig wlan0 up
	- wpa_supplicant -B -D wext -i wlan0 -c /etc/wpa_supplicant.conf
	- ifconfig wlan0 10.10.30.156 netmask 255.255.255.0 up
	- route add default gw 10.10.30.1
	- ping 10.10.30.1
	- ping 8.8.8.8

* 获得PC值
unsigned int pc;
asm volatile(
		\"1: la \$1, 1b\n\t\"
		\"sw \$1, %0\n\t\");

asm volatile(
		\"jal 1f\n\t\"
		\"nop\n\t\"
		\"1:\n\t\"
		\"move %0, \$31\n\t\"
		:\"=r\"(pc)::\"\$31\");

* alex
	- cd /mnt/tao/Documents/G_Tech/amazon/alexa/codes/alexa-avs-sample-app/samples/companionService
	- npm start
	- cd /mnt/tao/Documents/G_Tech/amazon/alexa/codes/alexa-avs-sample-app/samples/javaclient
	- mvn exec:exec

* wl 关闭rts
	wl ampdu_rts 0
	wl wme_ac sta be aifsn 2 ecwmin 3 ecwmax 3

* coredump
	set solib-search-path /mnt/tao/Documents/Y_customers/A_Ingenic/project/alexa/codes/repo/mozart/rootfs/updater/lib/:/mnt/tao/Documents/Y_customers/A_Ingenic/project/alexa/codes/repo/mozart/rootfs/app/lib:/mnt/tao/Documents/Y_customers/A_Ingenic/project/alexa/codes/repo/mozart/output/molib/app/usr/lib:/mnt/tao/Documents/Y_customers/A_Ingenic/project/alexa/codes/repo/mozart/output/molib/updater/usr/lib:/mnt/tao/Documents/Y_customers/A_Ingenic/project/alexa/codes/repo/mozart/output/mozart/app/usr/lib:/mnt/tao/Documents/Y_customers/A_Ingenic/project/alexa/codes/repo/mozart/output/mozart/app/usr/hcilib/

* indent
	indent -npro -kr -i8 -ts8 -sob -l100 -ss -ncs-cp1
"
