#!/bin/bash

ACT=echo

function scandir(){
#	echo 'ACT='$ACT
	local cur_dir parent_dir workdir
	workdir=$1
	cd ${workdir}

	if [ ${workdir} = "/" ]
	then
		cur_dir=""
	else
		cur_dir=$(pwd)
	fi

	for dirlist in $(ls ${cur_dir})
	do
		if test -d ${dirlist};then
			cd ${dirlist}
			scandir ${cur_dir}/${dirlist}
			cd ..
		else
			echo $ACT ${cur_dir}/${dirlist}
			$ACT ${cur_dir}/${dirlist}
		fi
	done
}

if test -d $2
then
	ACT=$1
	if [ "$2" = "" ]; then
		scandir .
	else
		scandir $2
	fi
elif test -d $1
then
	if [ $# -eq 2 ]; then
		ACT=$2
	fi
	if [ "$1" = "" ]; then
		scandir .
	else
		scandir $1
	fi
else
	echo "the Directory isn't exist which you input,pls input a new one!!"
exit 1
fi 

#myscandir "adb install" .
