#!/bin/bash

ACT=echo

function scandir(){
#	echo 'ACT='$ACT
	local cur_dir parent_dir workdir
	workdir=$1
	cd ${workdir}

	if [ ${workdir} = "/" ]
	then
		cur_dir=""
	else
		cur_dir=$(pwd)
	fi

	for dirlist in $(ls ${cur_dir})
	do
		if test -d ${dirlist};then
			cd ${dirlist}
			scandir ${cur_dir}/${dirlist}
			cd ..
		else
			echo /mnt/tao/Documents/A_AIP/codes/webrtc/build.x86-laiqu/Demo/asp_demo -c /mnt/tao/Documents/A_AIP/codes/webrtc/build.x86-laiqu/JzAsp_mono_dmic.json -n 1 -d 0 -i ${cur_dir}/${dirlist} -o /home/tao/Templates/laiqu/`basename ${cur_dir}/${dirlist} | sed "s/\.wav//"`-ns.wav
			echo /mnt/tao/Documents/A_AIP/codes/webrtc/webrtc-m/build/webrtc/modules/audio_processing/process_test -agc 1 -i /home/tao/Templates/laiqu/`basename ${cur_dir}/${dirlist} | sed "s/\.wav//"`-ns.wav -o /home/tao/Templates/laiqu/`basename ${cur_dir}/${dirlist} | sed "s/\.wav//"`-res.wav

			/mnt/tao/Documents/A_AIP/codes/webrtc/build.x86-laiqu/Demo/asp_demo -c /mnt/tao/Documents/A_AIP/codes/webrtc/build.x86-laiqu/JzAsp_mono_dmic.json -n 1 -d 0 -i ${cur_dir}/${dirlist} -o /home/tao/Templates/laiqu/`basename ${cur_dir}/${dirlist} | sed "s/\.wav//"`-ns.wav
			/mnt/tao/Documents/A_AIP/codes/webrtc/webrtc-m/build/webrtc/modules/audio_processing/process_test -agc 1 -i /home/tao/Templates/laiqu/`basename ${cur_dir}/${dirlist} | sed "s/\.wav//"`-ns.wav -o /home/tao/Templates/laiqu/`basename ${cur_dir}/${dirlist} | sed "s/\.wav//"`-res.wav
		fi
	done
}

if test -d $2
then
	ACT=$1
	if [ "$2" = "" ]; then
		scandir .
	else
		scandir $2
	fi
elif test -d $1
then
	if [ $# -eq 2 ]; then
		ACT=$2
	fi
	if [ "$1" = "" ]; then
		scandir .
	else
		scandir $1
	fi
else
	echo "the Directory isn't exist which you input,pls input a new one!!"
exit 1
fi 

#myscandir "adb install" .
